Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 125, in __init__
    fd = os.open(dev, os.O_RDWR | os.O_NONBLOCK)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/event13'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ryanford/ODTS-mini-Scan/Test/Capture_barcode.py", line 21, in <module>
    import barcode_reader
  File "/home/ryanford/ODTS-mini-Scan/Test/barcode_reader.py", line 20, in <module>
    dev = evdev.InputDevice('/dev/input/event13')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/evdev/device.py", line 127, in __init__
    fd = os.open(dev, os.O_RDONLY | os.O_NONBLOCK)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/input/event13'
